### ISSUE TITLE
traffic_counter.py not working with live video streaming.

### ISSUE THREAD

**Issue by PRAJWLSHETTY** [jorgem0/traffic_counter#2]
while run traffic_counter.py on live cameras I am getting the following error.
I tried with different camera IP addresses the codes is unable to display video it only display for 2 to 3 seconds and video stops in the live stream.

-3074457345618259.0 30.0 1920 1080
Traceback (most recent call last):
  File "C:\Users\OM_PRAJWL_NAMAHA\Desktop\github\imp\traffic_counter\traffic_counter.py", line 231, in <module>
    curcent = df.iloc[int(framenumber)][str(carids[currentcarsindex[i]])]
  File "C:\Program Files\Python36\lib\site-packages\pandas\core\indexing.py", line 1500, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "C:\Program Files\Python36\lib\site-packages\pandas\core\indexing.py", line 2230, in _getitem_axis
    self._validate_integer(key, axis)
  File "C:\Program Files\Python36\lib\site-packages\pandas\core\indexing.py", line 2139, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")

**Comment by fdornelasx** [comment]
I am getting this same error and didn't found a solution... This code is using pandas and the problem is the index of the dataframe.

**Comment by Harsha2102-code** [comment]
can u able to run the code for recorded video????
i got errors cn u help me??
